### ISSUE TITLE
Ability to pass a Markdown file as body

### ISSUE THREAD

**Issue by mremond** [tcnksm/ghr#109]
I think it would be useful to be able to pass a Markdown file as body.
It would allow more direct changelog generation automation.

It seems easier to manage than to pass long content from the command line.

**Comment by Songmu** [comment]
Thank you for registering the issue.

You can specify the file as below, is not it enough?

```console
% ghr -body="(cat ./release.md)" v0.1.0 dist
```

**Comment by mremond** [comment]
Yes, that should do. I did not thought of using `cat`
