### ISSUE TITLE
Does not works with GitHub Actions

### ISSUE THREAD

**Issue by ernitishkumar** [tcnksm/ghr#125]
I expected this to work with GitHub Actions.

But It seems it is not installing on GitHub Actions platform.

Hope we have an Action Wrapper release on GitHub Actions Marketplace for this.

**Comment by Wolveix** [comment]
`ghr` works great on GitHub Actions. In the following example, a Go environment is setup, cross-compiled using [Gox](https://github.com/mitchellh/gox), compressed, then uploaded using `ghr`.

```shell
name: Release
on: push

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Build Binaries
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - run: |
          mkdir -p builds/compressed
          go get github.com/mitchellh/gox
          gox --output "builds/drs-{{.OS}}-{{.Arch}}"
          cd builds
          find . -maxdepth 1 -type f -execdir zip 'compressed/{}.zip' '{}' \;
      - name: Upload Binaries
        run: |
          HASH=$(git rev-parse --short "$GITHUB_SHA")
          go get github.com/tcnksm/ghr
          ghr -t ${{ secrets.GITHUB_TOKEN }} -u ${{ github.actor }} -r ${{ github.event.repository.name }} --replace Latest builds/compressed/
```

**Comment by ernitishkumar** [comment]
Why ghr works out of the box in circleci but here we are requiring an external dependency i.e gox ?

**Comment by Wolveix** [comment]
You don't **need** to use [Gox](https://github.com/mitchellh/gox), I just use it to simplify building my Go project for various platforms.

**Comment by ernitishkumar** [comment]
Yaa got it working ! 

I was using the default `go` supplied by the github action runner i.e ` ubuntu-latest`

When I added this step
```
- name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
```
And manually installed `go` in my step `ghr` installed properly and it got resolved.
.
Thanks anyway for giving the hint as it helped me in figuring out the issue @Wolveix
