### ISSUE TITLE
failed to find assets (circleci)

### ISSUE THREAD

**Issue by VPraharsha03** [tcnksm/ghr#128]
Reference: https://circleci.com/blog/publishing-to-github-releases-via-circleci/
From the example given in the above blog post
```VERSION=${CIRCLE_TAG}
ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ./artifacts/
```
gives out the error: `Failed to find assets from ./artifacts/: no local assets are found` when publishing out the release

Do i need the additional step `store_artifacts` in `build:` ? and store to the `/artifacts` dir ?
eg: 
```
       - store_artifacts:
           path: ./artifacts
```

**Comment by rokibhasansagar** [comment]
@VPraharsha03, As they said in the blog,
> ./artifacts/ - Then we set the PATH to find the artifacts. In this case, everything in a directory called artifacts inside the current directory.

You definitely don't need to attach any workspace if you have only one job in a workflow.
Just replace the `./artifacts/` directory with the absolute/relative path of the file/folder that you want to upload as Release.

Example:
```bash
# To release multiple content from a folder 
ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} "/path/to/content_for_release_having_multiple_files/"
# To release a single file
ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} "/path/to/content_for_release/single_file_for_release"
```

**Comment by VPraharsha03** [comment]
@rokibhasansagar Yes, i kept two jobs earlier, now i've changed it to a single job, after some debugging and changes i could get things fixed.
