### ISSUE TITLE
Warning: '--prerelease' is deprecated, it will be removed soon. See usage.

### ISSUE THREAD

**Issue by tokuhirom** [tcnksm/ghr#23]
When I run `ghr -t XXX --prerelease ...`  command, ghr command says `Warning: '--prerelease' is deprecated, it will be removed soon. See usage.`.
But README.md and other docs recommend to use `--prerelease` option.

**Comment by tcnksm** [comment]
`--prerelease` option will not deprecated. 

This is because of wrong usage of flag package I use, I'll fix soon. Thanks.

**Comment by tcnksm** [comment]
Fix it
