### ISSUE TITLE
Remove deprecated code.google.com imports

### ISSUE THREAD

**Issue by EmileVauge** [tcnksm/ghr#25]
Hi,

As code.google.com is shutting down, I get a warning when using ghr:
```warning: code.google.com is shutting down; import path code.google.com/p/goauth2/oauth will stop working```.
Could you use ```golang.org/x/oauth2``` instead of ```code.google.com/p/goauth2/oauth``` here https://github.com/tcnksm/ghr/blob/351713cf89d7f23a568749625048e6ed333312bb/client.go#L8 ?

**Comment by tcnksm** [comment]
OK. Thank you for reporting
