### ISSUE TITLE
Documentation: what scopes are necessary for GitHub releases?

### ISSUE THREAD

**Issue by nathany** [tcnksm/ghr#37]
Is the repo scope needed, or is there a better option?

https://developer.github.com/v3/oauth/#scopes

**Comment by kwilczynski** [comment]
It would be nice to know what to check/uncheck when creating GitHub token too.

**Comment by BSick7** [comment]
I found my answer: https://docs.travis-ci.com/user/deployment/releases
`public_repo` or `repo`

**Comment by nathany** [comment]
thanks @BSick7

**Comment by tcnksm** [comment]
Thanks.

I updated `README.md` https://github.com/tcnksm/ghr/pull/40
