### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by hacdias** [tcnksm/ghr#41]
Hello,

I'm trying to setup ghr with Travis but I always receive this error:

```
ghr --username hacdias --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
POST https://api.github.com/repos/hacdias/journal/releases: 404 Not Found []
The command "ghr --username hacdias --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/" exited with 11.
```

Do you know what it can be?

**Comment by hacdias** [comment]
Ohh... it works now. I had to give more permissions to my token. Thanks anyway.

**Comment by JehandadK** [comment]
I hope we can use a better error message, since this is confusing. But unfortunately I think this is by design in Github.
