### ISSUE TITLE
Can not use GitHub Enterprise environment

### ISSUE THREAD

**Issue by griffin-stewie** [tcnksm/ghr#48]
ghr uploads to github.com when I'm using v0.5.0 even if I configured `$GITHUB_API`.
I read source code of v0.4.0, it seems that it extracts automatically `UploadURL` from returned value of go-github's `CreateRelease` method.

I hope fix this issue.

**Comment by tcnksm** [comment]
Hi, sorry for that. I fixed this but now I don't use GHE and can't test. 

Can you try to test ? Changes is in `feature/fix-48` branch.
After checkout that branch, and then `go install` and you can install patched version.

Thanks

**Comment by griffin-stewie** [comment]
@tcnksm 
Thank you your rapid response!
I'm gonna make sure it tomorrow.

**Comment by tcnksm** [comment]
Thanks.

**Comment by griffin-stewie** [comment]
@tcnksm 
I tested `feature/fix-48`, it works fine! Great!

I guess I found a tiny mistake. I'm gonna create new issue about it.

Anyway, This issue #48 was fixed by `feature/fix-48`.

Thanks a lot.

**Comment by tcnksm** [comment]
Thanks !
