### ISSUE TITLE
Format verbs shows up on output

### ISSUE THREAD

**Issue by griffin-stewie** [tcnksm/ghr#50]
Format verbs that it's like `%s` shows up on output.
It looks like bellow.

```sh
$ ghr -u myuser v0.1.0 pkg/dist
WARNING: found release (%s). Use existing one.
--> Uploading:   0.1.0_SHASUMS
--> Uploading: myawesometool_0.1.0_linux_amd64.zip
--> Uploading: myawesometool_0.1.0_darwin_amd64.zip
```

I think you forget to pass `*req.TagName` as seccond arguments of `fmt.Fprintln`.

**Comment by tcnksm** [comment]
Fixed, thanks

**Comment by tcnksm** [comment]
Release https://github.com/tcnksm/ghr/releases/tag/v0.5.1
