### ISSUE TITLE
package context: unrecognized import path "context" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by jritsema** [tcnksm/ghr#53]
Hi.  May be a golang noob question, but as of a few weeks ago, I noticed that `go get` started failing.  Any idea as to why?

```bash
$ go get github.com/tcnksm/ghr
package context: unrecognized import path "context" (import path does not begin with hostname)
```

**Comment by tcnksm** [comment]
Hi, thank you for submitting. Yes I changed some API but it's standard package. 
It seems you're using old go version. Cloud you upgrade to >= 1.7?

**Comment by jritsema** [comment]
Ok, thanks, I'll give that a try.

**Comment by jritsema** [comment]
Yep, I tested with 1.7.3 and it worked.  

You may want to consider mentioning in the readme that golang 1.7 or greater is a requirement.  

Thank you again for this very useful project!

**Comment by tcnksm** [comment]
Thank you for feedback. I updated documentation 

https://github.com/tcnksm/ghr/commit/3d153f0c4e7e1d645f3246cfc872883348b6cfc7
