### ISSUE TITLE
Give the option to use SSH credential

### ISSUE THREAD

**Issue by micky2be** [tcnksm/ghr#73]
We usually already have the ssh key setup on our local machine and gave an ssh key to CI.
Why not using that instead of creating an extra TOKEN?

**Comment by Songmu** [comment]
Since connecting over HTTPS is recommended by GitHub, and we will be using tokens on GitHub Actions, I think token support is sufficient.

https://docs.github.com/en/github/getting-started-with-github/quickstart/set-up-git
