### ISSUE TITLE
Isn't it insecure to use $GITHUB_TOKEN?

### ISSUE THREAD

**Issue by fredrikaverpil** [tcnksm/ghr#76]
Hi,

I'm running an open source project on Github which will automatically build PRs on Circle CI and I need to figure out a way to make artifacts get published to releases (whenever a tag is made). I'm considering using `ghr` to upload the artifacts, but I'm afraid an author of a malicions PR could edit the `.circleci/config.yml` to run `echo $GITHUB_TOKEN` and they'll get my token.

Did I completely misunderstand all of this, or is there some way to avoid getting the token into the wrong hands in my case?

**Comment by tcurdt** [comment]
At least when using travis, encrypted env variables are not available to PR or forks. I doubt this is any different with circle CI. Best check the docs of your CI provider.
IMO this issue isn't really much related to `ghr`.

**Comment by fredrikaverpil** [comment]
ok, thanks!
