### ISSUE TITLE
pass multiple files

### ISSUE THREAD

**Issue by tcurdt** [tcnksm/ghr#89]
Passing a dir (or a single file) feels a little brittle and inconvenient.
Is there any particular reason the CLI does not use the standard way?

    ghr tag file1 file2 file3 ...

Then `local*.go` would not even be necessary anymore.

**Comment by Songmu** [comment]
I see your opinion.

However, even if this is a slightly unnatural convention, the ghr has adopted this interface for a long time, and it is widely used, so I will not change it.

I think the ghr may accept multiple files without incompatible change, but I won't implement it myself, and you can write a patch.

Thank you.
